baseURL: 'https://timog.org/'
title: TIMOG
languageCode: en-us
pygmentsCodeFences: false
enableRobotsTXT: true
theme: hugo-flex
publishDir: public
paginate: 5
rssLimit: 10
timeout: 120000
summaryLength: 20

outputs:
  taxonomyTerm:
  - HTML
  taxonomy:
  - HTML
  section:
  - HTML

taxonomies:
  category: categories
  tag: tags
  kanji_radical: kanji_radical
  kanji_grade: kanji_grade
  kanji_strokes: kanji_strokes
  kanji_class: kanji_class
  kanji_reading: kanji_reading
  kanji_meaning: kanji_meaning
  kanji_jlpt: kanji_jlpt

permalinks:
  posts: /:filename/
  pages: /page/:filename/

params:
  author: 'Leon Timog'
  header: 'Timog'
  license: 'https://creativecommons.org/licenses/by-sa/4.0/'
  editURL: "https://github.com/tim0g/timog.org/tree/main/content"
  facebook: "timogjapan"
  color: "#1C86EE"
  width: 50rem
  description: "TIMOG: Wiki and Blog"
  footer: <small>All content ©Timog.org under <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="license">Creative Commons</a> license.</small></br><a href="#top">▲</a>
  rss: >-
    To subscribe to this RSS feed, copy the address in the address bar and paste
    it into your favorite feed reader.
  divider: false # Set to false to remove divider below posts on homepage
  opengraph: true
  twittercards: true
  summaries: false
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm: pathname
    theme: github-light
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  # css:                # Uncomment to add custom CSS from a list of files
  #   - css/foo.css
  #   - bar.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true

menu:
  nav:
    - name: Posts
      url: posts/
      weight: 1
    - name: Wiki
      url: wiki/
      weight: 2
    - name: Kanji
      url: kanji/
      weight: 3
    - name: Github
      url: https://github.com/tim0g/timog.org
      weight: 4
    - name: fb
      url: https://www.facebook.com/timogjapan/
      weight: 5