baseURL: 'https://timog.org/'
title: TIMOG
author: Leon Timog
languageCode: en-us
pygmentsCodeFences: false
enableRobotsTXT: true
theme: hugo-flex
publishDir: public
rssLimit: 10

outputs:
  taxonomyTerm:
  - HTML
  taxonomy:
  - HTML
  section:
  - HTML

permalinks:
  posts: '/:filename/'
  pages: '/:filename/'

params:
  editURL: "https://github.com/tim0g/tim/tree/main/content"
  color: "#1C86EE"
  width: 45rem
  description: "TIMOG: Guide, Wiki, Blog"
  footer: <small> <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://timog.org">Timog.org</a> by <span property="cc:attributionName">Leon Timog</span> is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Attribution 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p></small>
  rss: >-
    To subscribe to this RSS feed, copy the address in the address bar and paste
    it into your favorite feed reader.
  divider: false # Set to false to remove divider below posts on homepage
  schema: false
  opengraph: false
  twittercards: false
  summaries: false
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm: pathname
    theme: github-light
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  # css:                # Uncomment to add custom CSS from a list of files
  #   - css/foo.css
  #   - bar.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js



menu:
  nav:
    - name: About
      url: about-timog.org/
      weight: 1
    - name: Blog
      url: posts/
      weight: 2
    - name: Guide
      url: guide/
      weight: 3
